### ISSUE TITLE
[new feature] Highlighting 

### ISSUE THREAD

**Issue by eostis** [weaviate/weaviate#2567]
Would be nice to retrieve also the keyword highlighting in the field _additional.
As https://solr.apache.org/guide/solr/latest/query-guide/highlighting.html.

This is a very important feature for any WooCommerce application.
It can be used for all operators, including "Ask".

**Comment by ahmetugurmetus** [comment]
It will be also useful for people who are considering using weaviate instead of elasticsearch

**Comment by medihack** [comment]
Such a feature would be great. [Vespa.ai](https://vespa.ai/) does also support this in the form of [dynamic snippets](https://docs.vespa.ai/en/document-summaries.html) and [bolding](https://docs.vespa.ai/en/reference/schema-reference.html#bolding).

**Comment by eostis** [comment]
Indeed @medihack, I integrated Vespa.ai with WordPress in wpsolr.com with dynamic snippets and bolding.

**Comment by thearchitector** [comment]
this would be great

**Comment by dudanogueira** [comment]
Hi community! We are putting a bounty on this issue! Join us!
/bounty $200

**Comment by abhishek818** [comment]
@dudanogueira  @eostis 
Can you brief about the way we want this to implement OR provide a sample request with response.
Should highlighting support multiple fields, be case insensitive, or what other params are required?

Are we looking for something similar to below:
```

{
  Get {
    Article (
      nearText: {
        concepts: ["fashion"],
      }
    ) {
      title
      _additional {
        highlight {       <------------------
          title        
          product_description
      }
    }
  }
  
  Response:
  {
  "data": {
    "Get": {
      "Article": [
        {
          "_additional": {
            "distance": 0.15422738,
            "id": "e76ec9ae-1b84-3995-939a-1365b2215312"
          },
          "title": "2020's biggest fashion trends reflect a world in crisis",
          "product_description": "random text"
        },
        {
          "_additional": {
            "distance": 0.15683109,
            "id": "a2d51619-dd22-337a-8950-e1a407dab3d2"
          },
          "title": "How to Dress Up For a Fashion Holiday Season",
           "product_description": "random text fashion"
        },
      ]
    }
  }
  "highlighting": {
    "e76ec9ae-1b84-3995-939a-1365b2215312": {
      "manu": "2020's biggest <em>fashion</em> trends reflect a world in crisis "
    },
    "e76ec9ae-1b84-3995-939a-1365b2215312": {
      "product_description": "random text <em>fashion</em>"
    }
  }
```

**Comment by eostis** [comment]
Looks good to me. 

I usually use additional parameters:
- number of fragments
- fragment size (in characters).
- prefix ("<em>")
- postfix ("</em>")

Each fields would yield a list of (max number of fragments) fragments:
"product_description": ["surrounding text <em>fashion</em> surrounding text", "surrounding text <em>fashionable</em> surrounding text"]

In my client code, I finally concatenate fragments from each field for displaying.

**Comment by abhishek818** [comment]
@Subh231004 I didn't proceeded with this as I am not sure if maintainers of repo are active on bounty issues, you can see other bounty issues still open and inactive PRs. 

Upto you..

**Comment by parkerduckworth** [comment]
@abhishek818 hello :)

The bounty program is still active, we are just a bit behind on reviews. The existing PRs will be addressed shortly.

**Comment by abhishek818** [comment]
@parkerduckworth thanks for the heads up. Can you confirm with the requirement listed in comments [here](https://github.com/weaviate/weaviate/issues/2567#issuecomment-2109479052) and [here2](https://github.com/weaviate/weaviate/issues/2567#issuecomment-2109536972).

**Comment by JugalIwPtl** [comment]
is this bounty open or fixed ?

**Comment by abhishek818** [comment]
> @parkerduckworth thanks for the heads up. Can you or tag other repo owners to confirm with the requirement listed in comments [here](https://github.com/weaviate/weaviate/issues/2567#issuecomment-2109479052) and [here2](https://github.com/weaviate/weaviate/issues/2567#issuecomment-2109536972).

@parkerduckworth just bumping this 
@antas-marcin @dirkkul  (tagging some active maintainers, sorry for the mentions)

**Comment by adilkadivala** [comment]
is this issue still open ?

**Comment by harshagrawal-bit** [comment]
is this bounty still open and are the maintainers active for the bounty

**Comment by matiasmagni** [comment]
/claim #2567

# Implementation Plan: Highlighting Feature for Issue #2567

## Objective

Add a highlighting feature (similar to Solr) that returns matching text snippets in search results. This should support **BM25**, **hybrid search**, and other keyword-based queries.

---

## 1. Core Data Structures

### `entities/additional/highlight.go` (New File)

Add the `Highlight` struct to define the structure of the returned snippets:

```go
type Highlight struct {
    Property  string   `json:"property"`
    Fragments []string `json:"fragments"` // highlighted text snippets
}

```

### `entities/additional/classification.go`

Update the `Properties` struct to include the toggle:

```go
type Properties struct {
    // ... existing fields
    Highlight bool `json:"highlight"`
}

```

---

## 2. GraphQL API Updates

### `adapters/handlers/graphql/local/get/class_builder.go`

* Add `highlight` field to additional fields.
* Implement the `additionalHighlightField()` method.

### `adapters/handlers/graphql/local/get/class_builder_fields.go`

* Add `highlight` to the `isAdditional()` check.
* Implement extraction logic for the following input parameters:

| Parameter | Type | Description | Default |
| --- | --- | --- | --- |
| `highlight` | Boolean | Enables the highlighting feature | `false` |
| `highlightFragments` | Integer | Number of fragments to return | `1` |
| `highlightFragmentSeparator` | String | String used to join fragments | `...` |
| `highlightProperty` | String | Specific property to highlight | Optional |

---

## 3. Backend Implementation

### `adapters/repos/db/inverted/bm25_searcher.go`

The core logic resides here. During the scoring phase, the system must:

1. **Track Terms:** Identify which query terms matched specific documents.
2. **Fetch Content:** Retrieve the original text for those documents.
3. **Generate Snippets:** Use term positions to create fragments with `<em>` tags.

**Key Functions:**

* `extractMatchingTerms()`: Identifies matching query terms per document.
* `generateHighlightedFragments()`: Handles the string manipulation for snippet creation.
* **Storage:** Results are stored in `result.AdditionalProperties["highlight"]`.

---

## 4. Result Structure Example

```json
{
  "Get": {
    "Article": [
      {
        "title": "My Article",
        "content": "The quick brown fox...",
        "_additional": {
          "highlight": [
            {
              "property": "content",
              "fragments": ["The <em>quick</em> brown fox..."]
            }
          ]
        }
      }
    ]
  }
}

```

---

## 5. Files to Modify

| File | Changes |
| --- | --- |
| `entities/additional/classification.go` | Add `Highlight` bool field |
| `entities/additional/highlight.go` | **NEW** - Create `Highlight` struct |
| `adapters/handlers/graphql/local/get/class_builder.go` | Add highlight GraphQL field |
| `adapters/handlers/graphql/local/get/class_builder_fields.go` | Add highlight extraction |
| `adapters/repos/db/inverted/bm25_searcher.go` | Implement highlight generation |
| `adapters/repos/db/inverted/bm25_searcher_block.go` | Block-based highlighting |
| `usecases/traverser/explorer.go` | Populate highlights in results |
| `entities/search/result.go` | Add `Highlight` field to `Result` |

---

## 6. Proposed Task List

* [ ] Create `entities/additional/highlight.go` with `Highlight` struct
* [ ] Add `Highlight` field to `entities/additional/classification.go`
* [ ] Add GraphQL field in `class_builder.go`
* [ ] Add field extraction in `class_builder_fields.go`
* [ ] Implement highlight generation in `BM25 searcher`
* [ ] Add highlighting for hybrid search
* [ ] Populate highlights in explorer results
* [ ] Add unit tests for highlighting logic
* [ ] Add integration tests for end-to-end highlighting

---

## 7. Considerations

* **Fragment Size:** Implement a limit on fragment length to prevent bloated API payloads.
* **Fragment Count:** Ensure users can configure how many snippets they receive per property.
* **Multi-property:** Ensure the logic iterates correctly over multiple requested properties.
* **Performance:** Use **lazy-loading** for the original document text; only fetch it if the `highlight` flag is explicitly requested.

**Comment by matiasmagni** [comment]
/claim #2567 -> PR #10775

@eostis please take a look!

**Comment by TrixterYT00001** [comment]
Hey! I see the discussion on the highlighting parameters. I'd like to attempt this—I'm a student dev and I've been working on mobile-optimized data simulations (check my projectile-physics-cli repo).
I'm particularly interested in handling the prefix/postfix logic for the fragments. I'm ready to dive into the codebase tonight. 
/attempt #2567

**Comment by 1s44c-0** [comment]
Hi I’d like to work on this issue.

My plan is to implement a highlighting feature by extracting matched query terms from the search results and returning them as a highlight field in the response.

Please let me know if this approach aligns with your expectations.

**Comment by Sujal222007** [comment]
I'm a Python developer. I’ve already developed a prototype for the highlighting logic using Regex to handle case-insensitivity and context-snapping (snippet generation). I’d like to implement this into the Weaviate Python client. Can I take this up?

**Comment by devman247** [comment]
Hi, I am interested in solving this issue. Please send me an invitation to join.

**Comment by aimqwest** [comment]
/attempt I can take this highlight feature issue and submit a focused PR with tests.

**Comment by aimqwest** [comment]
/attempt #2567\n\nAIMQWEST implementation plan: add _additional.highlight support with configurable fields/fragments/tags, include tests + docs.

**Comment by dirkkul** [comment]
We're moving away from GQL, so adding this does not make sense anymore
