### ISSUE TITLE
Async indexing

### ISSUE THREAD

**Issue by asdine** [weaviate/weaviate#3541]
https://github.com/weaviate/weaviate/pull/3424 introduced a basic implementation of async indexing that needs to be improved to be production ready.

Here is a list of tasks and feedbask collected during the review and testing process:

### Tasks

- [x] Add queue size metric
- [x] Index vectors after a certain period of time in the queue
- [x] Reduce startup loading time of unindexed vectors by skipping already indexed vectors in the store #3568 
- [x] Add shard status to indicate that the node is still indexing or the indexing is done https://github.com/weaviate/weaviate/pull/3596
- [x] Make the queue compatible with PQ
