### ISSUE TITLE
Update location type in schema-specs and implementation

### ISSUE THREAD

**Issue by bobvanluijt** [weaviate/weaviate#677]
Relating to the P2P network and how we display the location of a concept.

**Current:**

```json
{
	"schema": {
		"inCity": {
			"$cref": "cfd0b3ea-9128-4fe5-a024-b7e68fe22206",
			"locationUrl": "http://localhost",
			"type": "Thing"
		}
	}
}
```

**New:**

```json
{
	"schema": {
		"inCity": {
			"$cref": "weaviate+http://weaviate-a/cfd0b3ea-9128-4fe5-a024-b7e68fe22206"
		}
	}
}
```

Where `weaviate-a` also can be `localhost`.

**Important:**

This should also be reflected in the open-api schema and while creating concepts (id est, things or actions).

**Comment by bobvanluijt** [comment]
@laura-ham: FYI, can you take this into account in the prototype?
@dljcollette: FYI, does the above have an impact on your work?

**Comment by etiennedi** [comment]
@bobvanluijt 

The above actually contains two changes with somewhat different implications:

## Systems affected / Effort to change

**Change 1: Merge location into `$cref`**
This change is straight-forward, we just have to parse one field instead of two, extract the right info in a few places, adapt all our test data, etc. This should be less than a days work. However, I do some conceptual input, see section "API discussion" below.

**Change 2: We are removing the type field**
This is a relatively big change. Why? We currently don't have a means to receive a "thing or action by id". Neither on the db connector - which is relevant for local refs -, nor on the rest api - which is relevant for network refs. We can only retrieve the data if we know that something is either a thing or an action. So we have to either:

**Change 2a** add such a feature, which means adding to the connectors and to the rest api, then changing how the refs are consumed. Careful estimation: about a week

**Change 2b** we could just include the info in the locations string. So instead of
```
weaviate+http://weaviate-a/cfd0b3ea-9128-4fe5-a024-b7e68fe22206
```
we would have:
```
weaviate+http://weaviate-a/things/cfd0b3ea-9128-4fe5-a024-b7e68fe22206

Besides being much less effort it would also be consistent with the URI structure of the rest API. If you want to retrieve a thing by id the URI would also be `/weaviate/v1/thing/<uuid>`.

## API discussion

I'm not sold on the `weaviate+http` scheme yet. I know including the actual transfer protocol was also based on my input, but here's the problem I currently see: A peer must first register into the network via the Genesis/Keyper. During registration it already provides it's discovery information. This is why we can (in GraphQL and in Refs) just reference this peer as `weaviateA` rather than `https://weaviateA.some-subdomain.superlongdomain-in-some-enterprise-network:30576`. This discovery information already contains a protocol - in my example above it's `https`. I don't see any added value if each reference should again contain the protocol. Let's say during an experimental phase a customer sets up weaviate without `https` and then decideds to move everything to `https` once the experiment transitions into production code. If each cross-ref contained the protocol as well, we'd now have to update every cross-ref. If the cross-ref omits the protocol, they are still valid and the info from the Genesis/Keyper simply tells all the instances to use the up-to-date protocol.

### So I'm proposing (change 3):

Instead of 
```
weaviate+http://weaviate-a/cfd0b3ea-9128-4fe5-a024-b7e68fe22206
```
Let's simply have 
```
weaviate://weaviate-a/cfd0b3ea-9128-4fe5-a024-b7e68fe22206
```

#### Advantages
- Easy to changed when moving as extensively outlined above
- More pluggability on the network: Why should the business items know that it's in a HTTP(S) network? Maybe at some point it could change from an HTTP-based network to an RPC or even Ethereum network. 

## I would like Feedback on
1. What is preferred way between proposed change 2a (more effort, but completely agnostic of kind) vs. 2b (less effort and more consistent API design)?
2. Change 3, i.e. `weaviate+http://` vs. `weaviate://`?

**Comment by bobvanluijt** [comment]
Thanks for the detailed feedback @etiennedi. Also agreed with your points. 

To answer your questions in one; I really like `weaviate://weaviate-a/things/cfd0b3ea-9128-4fe5-a024-b7e68fe22206` because it is in line with the schema.

**Comment by etiennedi** [comment]
Awesome, great to hear. This will move to No.1 on my priority list, then.

**Comment by dljcollette** [comment]
@bobvanluijt will this impact the GraphQL schema or is this a reference for the GraphQL resolvers?

**Comment by etiennedi** [comment]
@dljcollette This should have no influence on the the graphQL schema, it should only affect how `Things` and `Actions` are added to weaviate (and updated).

**Comment by etiennedi** [comment]
## Todos

* [ ] update importer script to new format and see where it crashes
* [ ] fix all places where it crashes
  * sub-items to be added here once I know more
* [ ] deal with "capitalization conflict" (no rights reserved on this awesome name
  * To quote on mself on what this is about: 
    > Note that there's currently a bit of confusion about capitalization of
refProps, such as "InCountry". On user-facing parts we have them
uppercased, but on schema imports (and therefore in the database) they
are lowercased like "inCountry". I don't really see a reason for that
and it currently leads to some ugly transformations, such as
string.Title() being used, when displaying the prop and untitle(), i.e. a
custom untitling function, being used when taking in user input.

**Comment by etiennedi** [comment]
@bobvanluijt  This is technically complete, but it wasn't possible to complete this without starting to remove the Key-Auth (see #646) already in parts. So I'll now move on to #646 and then create a PR for both instead of trying to merge it already now.
